// Code generated by ent, DO NOT EDIT.

package ldapconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ldapconfig type in the database.
	Label = "ldap_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldServerURL holds the string denoting the server_url field in the database.
	FieldServerURL = "server_url"
	// FieldBindDn holds the string denoting the bind_dn field in the database.
	FieldBindDn = "bind_dn"
	// FieldBindPasswordEncrypted holds the string denoting the bind_password_encrypted field in the database.
	FieldBindPasswordEncrypted = "bind_password_encrypted"
	// FieldBaseDn holds the string denoting the base_dn field in the database.
	FieldBaseDn = "base_dn"
	// FieldUserFilter holds the string denoting the user_filter field in the database.
	FieldUserFilter = "user_filter"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldTLSEnabled holds the string denoting the tls_enabled field in the database.
	FieldTLSEnabled = "tls_enabled"
	// FieldTLSSkipVerify holds the string denoting the tls_skip_verify field in the database.
	FieldTLSSkipVerify = "tls_skip_verify"
	// FieldConfigSource holds the string denoting the config_source field in the database.
	FieldConfigSource = "config_source"
	// Table holds the table name of the ldapconfig in the database.
	Table = "ldap_configs"
)

// Columns holds all SQL columns for ldapconfig fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldServerURL,
	FieldBindDn,
	FieldBindPasswordEncrypted,
	FieldBaseDn,
	FieldUserFilter,
	FieldEnabled,
	FieldTLSEnabled,
	FieldTLSSkipVerify,
	FieldConfigSource,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ServerURLValidator is a validator for the "server_url" field. It is called by the builders before save.
	ServerURLValidator func(string) error
	// BindDnValidator is a validator for the "bind_dn" field. It is called by the builders before save.
	BindDnValidator func(string) error
	// BindPasswordEncryptedValidator is a validator for the "bind_password_encrypted" field. It is called by the builders before save.
	BindPasswordEncryptedValidator func(string) error
	// BaseDnValidator is a validator for the "base_dn" field. It is called by the builders before save.
	BaseDnValidator func(string) error
	// DefaultUserFilter holds the default value on creation for the "user_filter" field.
	DefaultUserFilter string
	// UserFilterValidator is a validator for the "user_filter" field. It is called by the builders before save.
	UserFilterValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultTLSEnabled holds the default value on creation for the "tls_enabled" field.
	DefaultTLSEnabled bool
	// DefaultTLSSkipVerify holds the default value on creation for the "tls_skip_verify" field.
	DefaultTLSSkipVerify bool
	// DefaultConfigSource holds the default value on creation for the "config_source" field.
	DefaultConfigSource string
	// ConfigSourceValidator is a validator for the "config_source" field. It is called by the builders before save.
	ConfigSourceValidator func(string) error
)

// OrderOption defines the ordering options for the LdapConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByServerURL orders the results by the server_url field.
func ByServerURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServerURL, opts...).ToFunc()
}

// ByBindDn orders the results by the bind_dn field.
func ByBindDn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindDn, opts...).ToFunc()
}

// ByBindPasswordEncrypted orders the results by the bind_password_encrypted field.
func ByBindPasswordEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindPasswordEncrypted, opts...).ToFunc()
}

// ByBaseDn orders the results by the base_dn field.
func ByBaseDn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseDn, opts...).ToFunc()
}

// ByUserFilter orders the results by the user_filter field.
func ByUserFilter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserFilter, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByTLSEnabled orders the results by the tls_enabled field.
func ByTLSEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTLSEnabled, opts...).ToFunc()
}

// ByTLSSkipVerify orders the results by the tls_skip_verify field.
func ByTLSSkipVerify(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTLSSkipVerify, opts...).ToFunc()
}

// ByConfigSource orders the results by the config_source field.
func ByConfigSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigSource, opts...).ToFunc()
}
