// Code generated by ent, DO NOT EDIT.

package ldapconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// ServerURL applies equality check predicate on the "server_url" field. It's identical to ServerURLEQ.
func ServerURL(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldServerURL, v))
}

// BindDn applies equality check predicate on the "bind_dn" field. It's identical to BindDnEQ.
func BindDn(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBindDn, v))
}

// BindPasswordEncrypted applies equality check predicate on the "bind_password_encrypted" field. It's identical to BindPasswordEncryptedEQ.
func BindPasswordEncrypted(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBindPasswordEncrypted, v))
}

// BaseDn applies equality check predicate on the "base_dn" field. It's identical to BaseDnEQ.
func BaseDn(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBaseDn, v))
}

// UserFilter applies equality check predicate on the "user_filter" field. It's identical to UserFilterEQ.
func UserFilter(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldUserFilter, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldEnabled, v))
}

// TLSEnabled applies equality check predicate on the "tls_enabled" field. It's identical to TLSEnabledEQ.
func TLSEnabled(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldTLSEnabled, v))
}

// TLSSkipVerify applies equality check predicate on the "tls_skip_verify" field. It's identical to TLSSkipVerifyEQ.
func TLSSkipVerify(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldTLSSkipVerify, v))
}

// ConfigSource applies equality check predicate on the "config_source" field. It's identical to ConfigSourceEQ.
func ConfigSource(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldConfigSource, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// ServerURLEQ applies the EQ predicate on the "server_url" field.
func ServerURLEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldServerURL, v))
}

// ServerURLNEQ applies the NEQ predicate on the "server_url" field.
func ServerURLNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldServerURL, v))
}

// ServerURLIn applies the In predicate on the "server_url" field.
func ServerURLIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldServerURL, vs...))
}

// ServerURLNotIn applies the NotIn predicate on the "server_url" field.
func ServerURLNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldServerURL, vs...))
}

// ServerURLGT applies the GT predicate on the "server_url" field.
func ServerURLGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldServerURL, v))
}

// ServerURLGTE applies the GTE predicate on the "server_url" field.
func ServerURLGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldServerURL, v))
}

// ServerURLLT applies the LT predicate on the "server_url" field.
func ServerURLLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldServerURL, v))
}

// ServerURLLTE applies the LTE predicate on the "server_url" field.
func ServerURLLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldServerURL, v))
}

// ServerURLContains applies the Contains predicate on the "server_url" field.
func ServerURLContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldServerURL, v))
}

// ServerURLHasPrefix applies the HasPrefix predicate on the "server_url" field.
func ServerURLHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldServerURL, v))
}

// ServerURLHasSuffix applies the HasSuffix predicate on the "server_url" field.
func ServerURLHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldServerURL, v))
}

// ServerURLEqualFold applies the EqualFold predicate on the "server_url" field.
func ServerURLEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldServerURL, v))
}

// ServerURLContainsFold applies the ContainsFold predicate on the "server_url" field.
func ServerURLContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldServerURL, v))
}

// BindDnEQ applies the EQ predicate on the "bind_dn" field.
func BindDnEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBindDn, v))
}

// BindDnNEQ applies the NEQ predicate on the "bind_dn" field.
func BindDnNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldBindDn, v))
}

// BindDnIn applies the In predicate on the "bind_dn" field.
func BindDnIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldBindDn, vs...))
}

// BindDnNotIn applies the NotIn predicate on the "bind_dn" field.
func BindDnNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldBindDn, vs...))
}

// BindDnGT applies the GT predicate on the "bind_dn" field.
func BindDnGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldBindDn, v))
}

// BindDnGTE applies the GTE predicate on the "bind_dn" field.
func BindDnGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldBindDn, v))
}

// BindDnLT applies the LT predicate on the "bind_dn" field.
func BindDnLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldBindDn, v))
}

// BindDnLTE applies the LTE predicate on the "bind_dn" field.
func BindDnLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldBindDn, v))
}

// BindDnContains applies the Contains predicate on the "bind_dn" field.
func BindDnContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldBindDn, v))
}

// BindDnHasPrefix applies the HasPrefix predicate on the "bind_dn" field.
func BindDnHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldBindDn, v))
}

// BindDnHasSuffix applies the HasSuffix predicate on the "bind_dn" field.
func BindDnHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldBindDn, v))
}

// BindDnEqualFold applies the EqualFold predicate on the "bind_dn" field.
func BindDnEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldBindDn, v))
}

// BindDnContainsFold applies the ContainsFold predicate on the "bind_dn" field.
func BindDnContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldBindDn, v))
}

// BindPasswordEncryptedEQ applies the EQ predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedNEQ applies the NEQ predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedIn applies the In predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldBindPasswordEncrypted, vs...))
}

// BindPasswordEncryptedNotIn applies the NotIn predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldBindPasswordEncrypted, vs...))
}

// BindPasswordEncryptedGT applies the GT predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedGTE applies the GTE predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedLT applies the LT predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedLTE applies the LTE predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedContains applies the Contains predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedHasPrefix applies the HasPrefix predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedHasSuffix applies the HasSuffix predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedEqualFold applies the EqualFold predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldBindPasswordEncrypted, v))
}

// BindPasswordEncryptedContainsFold applies the ContainsFold predicate on the "bind_password_encrypted" field.
func BindPasswordEncryptedContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldBindPasswordEncrypted, v))
}

// BaseDnEQ applies the EQ predicate on the "base_dn" field.
func BaseDnEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldBaseDn, v))
}

// BaseDnNEQ applies the NEQ predicate on the "base_dn" field.
func BaseDnNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldBaseDn, v))
}

// BaseDnIn applies the In predicate on the "base_dn" field.
func BaseDnIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldBaseDn, vs...))
}

// BaseDnNotIn applies the NotIn predicate on the "base_dn" field.
func BaseDnNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldBaseDn, vs...))
}

// BaseDnGT applies the GT predicate on the "base_dn" field.
func BaseDnGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldBaseDn, v))
}

// BaseDnGTE applies the GTE predicate on the "base_dn" field.
func BaseDnGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldBaseDn, v))
}

// BaseDnLT applies the LT predicate on the "base_dn" field.
func BaseDnLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldBaseDn, v))
}

// BaseDnLTE applies the LTE predicate on the "base_dn" field.
func BaseDnLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldBaseDn, v))
}

// BaseDnContains applies the Contains predicate on the "base_dn" field.
func BaseDnContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldBaseDn, v))
}

// BaseDnHasPrefix applies the HasPrefix predicate on the "base_dn" field.
func BaseDnHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldBaseDn, v))
}

// BaseDnHasSuffix applies the HasSuffix predicate on the "base_dn" field.
func BaseDnHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldBaseDn, v))
}

// BaseDnEqualFold applies the EqualFold predicate on the "base_dn" field.
func BaseDnEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldBaseDn, v))
}

// BaseDnContainsFold applies the ContainsFold predicate on the "base_dn" field.
func BaseDnContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldBaseDn, v))
}

// UserFilterEQ applies the EQ predicate on the "user_filter" field.
func UserFilterEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldUserFilter, v))
}

// UserFilterNEQ applies the NEQ predicate on the "user_filter" field.
func UserFilterNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldUserFilter, v))
}

// UserFilterIn applies the In predicate on the "user_filter" field.
func UserFilterIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldUserFilter, vs...))
}

// UserFilterNotIn applies the NotIn predicate on the "user_filter" field.
func UserFilterNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldUserFilter, vs...))
}

// UserFilterGT applies the GT predicate on the "user_filter" field.
func UserFilterGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldUserFilter, v))
}

// UserFilterGTE applies the GTE predicate on the "user_filter" field.
func UserFilterGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldUserFilter, v))
}

// UserFilterLT applies the LT predicate on the "user_filter" field.
func UserFilterLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldUserFilter, v))
}

// UserFilterLTE applies the LTE predicate on the "user_filter" field.
func UserFilterLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldUserFilter, v))
}

// UserFilterContains applies the Contains predicate on the "user_filter" field.
func UserFilterContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldUserFilter, v))
}

// UserFilterHasPrefix applies the HasPrefix predicate on the "user_filter" field.
func UserFilterHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldUserFilter, v))
}

// UserFilterHasSuffix applies the HasSuffix predicate on the "user_filter" field.
func UserFilterHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldUserFilter, v))
}

// UserFilterEqualFold applies the EqualFold predicate on the "user_filter" field.
func UserFilterEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldUserFilter, v))
}

// UserFilterContainsFold applies the ContainsFold predicate on the "user_filter" field.
func UserFilterContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldUserFilter, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldEnabled, v))
}

// TLSEnabledEQ applies the EQ predicate on the "tls_enabled" field.
func TLSEnabledEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldTLSEnabled, v))
}

// TLSEnabledNEQ applies the NEQ predicate on the "tls_enabled" field.
func TLSEnabledNEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldTLSEnabled, v))
}

// TLSSkipVerifyEQ applies the EQ predicate on the "tls_skip_verify" field.
func TLSSkipVerifyEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldTLSSkipVerify, v))
}

// TLSSkipVerifyNEQ applies the NEQ predicate on the "tls_skip_verify" field.
func TLSSkipVerifyNEQ(v bool) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldTLSSkipVerify, v))
}

// ConfigSourceEQ applies the EQ predicate on the "config_source" field.
func ConfigSourceEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEQ(FieldConfigSource, v))
}

// ConfigSourceNEQ applies the NEQ predicate on the "config_source" field.
func ConfigSourceNEQ(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNEQ(FieldConfigSource, v))
}

// ConfigSourceIn applies the In predicate on the "config_source" field.
func ConfigSourceIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldIn(FieldConfigSource, vs...))
}

// ConfigSourceNotIn applies the NotIn predicate on the "config_source" field.
func ConfigSourceNotIn(vs ...string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldNotIn(FieldConfigSource, vs...))
}

// ConfigSourceGT applies the GT predicate on the "config_source" field.
func ConfigSourceGT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGT(FieldConfigSource, v))
}

// ConfigSourceGTE applies the GTE predicate on the "config_source" field.
func ConfigSourceGTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldGTE(FieldConfigSource, v))
}

// ConfigSourceLT applies the LT predicate on the "config_source" field.
func ConfigSourceLT(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLT(FieldConfigSource, v))
}

// ConfigSourceLTE applies the LTE predicate on the "config_source" field.
func ConfigSourceLTE(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldLTE(FieldConfigSource, v))
}

// ConfigSourceContains applies the Contains predicate on the "config_source" field.
func ConfigSourceContains(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContains(FieldConfigSource, v))
}

// ConfigSourceHasPrefix applies the HasPrefix predicate on the "config_source" field.
func ConfigSourceHasPrefix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasPrefix(FieldConfigSource, v))
}

// ConfigSourceHasSuffix applies the HasSuffix predicate on the "config_source" field.
func ConfigSourceHasSuffix(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldHasSuffix(FieldConfigSource, v))
}

// ConfigSourceEqualFold applies the EqualFold predicate on the "config_source" field.
func ConfigSourceEqualFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldEqualFold(FieldConfigSource, v))
}

// ConfigSourceContainsFold applies the ContainsFold predicate on the "config_source" field.
func ConfigSourceContainsFold(v string) predicate.LdapConfig {
	return predicate.LdapConfig(sql.FieldContainsFold(FieldConfigSource, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LdapConfig) predicate.LdapConfig {
	return predicate.LdapConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LdapConfig) predicate.LdapConfig {
	return predicate.LdapConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LdapConfig) predicate.LdapConfig {
	return predicate.LdapConfig(sql.NotPredicates(p))
}
