// Code generated by ent, DO NOT EDIT.

package ldapuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the ldapuser type in the database.
	Label = "ldap_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLdapUsername holds the string denoting the ldap_username field in the database.
	FieldLdapUsername = "ldap_username"
	// FieldLdapDn holds the string denoting the ldap_dn field in the database.
	FieldLdapDn = "ldap_dn"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the ldapuser in the database.
	Table = "ldap_users"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "ldap_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for ldapuser fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldLdapUsername,
	FieldLdapDn,
	FieldLastSyncAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// LdapUsernameValidator is a validator for the "ldap_username" field. It is called by the builders before save.
	LdapUsernameValidator func(string) error
	// LdapDnValidator is a validator for the "ldap_dn" field. It is called by the builders before save.
	LdapDnValidator func(string) error
	// DefaultLastSyncAt holds the default value on creation for the "last_sync_at" field.
	DefaultLastSyncAt func() time.Time
)

// OrderOption defines the ordering options for the LdapUser queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLdapUsername orders the results by the ldap_username field.
func ByLdapUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLdapUsername, opts...).ToFunc()
}

// ByLdapDn orders the results by the ldap_dn field.
func ByLdapDn(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLdapDn, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
