// Code generated by ent, DO NOT EDIT.

package ldapuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldUserID, v))
}

// LdapUsername applies equality check predicate on the "ldap_username" field. It's identical to LdapUsernameEQ.
func LdapUsername(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLdapUsername, v))
}

// LdapDn applies equality check predicate on the "ldap_dn" field. It's identical to LdapDnEQ.
func LdapDn(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLdapDn, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLastSyncAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldUserID, vs...))
}

// LdapUsernameEQ applies the EQ predicate on the "ldap_username" field.
func LdapUsernameEQ(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLdapUsername, v))
}

// LdapUsernameNEQ applies the NEQ predicate on the "ldap_username" field.
func LdapUsernameNEQ(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldLdapUsername, v))
}

// LdapUsernameIn applies the In predicate on the "ldap_username" field.
func LdapUsernameIn(vs ...string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldLdapUsername, vs...))
}

// LdapUsernameNotIn applies the NotIn predicate on the "ldap_username" field.
func LdapUsernameNotIn(vs ...string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldLdapUsername, vs...))
}

// LdapUsernameGT applies the GT predicate on the "ldap_username" field.
func LdapUsernameGT(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldLdapUsername, v))
}

// LdapUsernameGTE applies the GTE predicate on the "ldap_username" field.
func LdapUsernameGTE(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldLdapUsername, v))
}

// LdapUsernameLT applies the LT predicate on the "ldap_username" field.
func LdapUsernameLT(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldLdapUsername, v))
}

// LdapUsernameLTE applies the LTE predicate on the "ldap_username" field.
func LdapUsernameLTE(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldLdapUsername, v))
}

// LdapUsernameContains applies the Contains predicate on the "ldap_username" field.
func LdapUsernameContains(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldContains(FieldLdapUsername, v))
}

// LdapUsernameHasPrefix applies the HasPrefix predicate on the "ldap_username" field.
func LdapUsernameHasPrefix(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldHasPrefix(FieldLdapUsername, v))
}

// LdapUsernameHasSuffix applies the HasSuffix predicate on the "ldap_username" field.
func LdapUsernameHasSuffix(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldHasSuffix(FieldLdapUsername, v))
}

// LdapUsernameEqualFold applies the EqualFold predicate on the "ldap_username" field.
func LdapUsernameEqualFold(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEqualFold(FieldLdapUsername, v))
}

// LdapUsernameContainsFold applies the ContainsFold predicate on the "ldap_username" field.
func LdapUsernameContainsFold(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldContainsFold(FieldLdapUsername, v))
}

// LdapDnEQ applies the EQ predicate on the "ldap_dn" field.
func LdapDnEQ(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLdapDn, v))
}

// LdapDnNEQ applies the NEQ predicate on the "ldap_dn" field.
func LdapDnNEQ(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldLdapDn, v))
}

// LdapDnIn applies the In predicate on the "ldap_dn" field.
func LdapDnIn(vs ...string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldLdapDn, vs...))
}

// LdapDnNotIn applies the NotIn predicate on the "ldap_dn" field.
func LdapDnNotIn(vs ...string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldLdapDn, vs...))
}

// LdapDnGT applies the GT predicate on the "ldap_dn" field.
func LdapDnGT(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldLdapDn, v))
}

// LdapDnGTE applies the GTE predicate on the "ldap_dn" field.
func LdapDnGTE(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldLdapDn, v))
}

// LdapDnLT applies the LT predicate on the "ldap_dn" field.
func LdapDnLT(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldLdapDn, v))
}

// LdapDnLTE applies the LTE predicate on the "ldap_dn" field.
func LdapDnLTE(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldLdapDn, v))
}

// LdapDnContains applies the Contains predicate on the "ldap_dn" field.
func LdapDnContains(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldContains(FieldLdapDn, v))
}

// LdapDnHasPrefix applies the HasPrefix predicate on the "ldap_dn" field.
func LdapDnHasPrefix(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldHasPrefix(FieldLdapDn, v))
}

// LdapDnHasSuffix applies the HasSuffix predicate on the "ldap_dn" field.
func LdapDnHasSuffix(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldHasSuffix(FieldLdapDn, v))
}

// LdapDnEqualFold applies the EqualFold predicate on the "ldap_dn" field.
func LdapDnEqualFold(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEqualFold(FieldLdapDn, v))
}

// LdapDnContainsFold applies the ContainsFold predicate on the "ldap_dn" field.
func LdapDnContainsFold(v string) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldContainsFold(FieldLdapDn, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.LdapUser {
	return predicate.LdapUser(sql.FieldLTE(FieldLastSyncAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.LdapUser {
	return predicate.LdapUser(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.LdapUser {
	return predicate.LdapUser(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LdapUser) predicate.LdapUser {
	return predicate.LdapUser(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LdapUser) predicate.LdapUser {
	return predicate.LdapUser(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LdapUser) predicate.LdapUser {
	return predicate.LdapUser(sql.NotPredicates(p))
}
