// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ldapuser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LdapUserCreate is the builder for creating a LdapUser entity.
type LdapUserCreate struct {
	config
	mutation *LdapUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LdapUserCreate) SetCreatedAt(v time.Time) *LdapUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LdapUserCreate) SetNillableCreatedAt(v *time.Time) *LdapUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LdapUserCreate) SetUpdatedAt(v time.Time) *LdapUserCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LdapUserCreate) SetNillableUpdatedAt(v *time.Time) *LdapUserCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *LdapUserCreate) SetUserID(v int64) *LdapUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetLdapUsername sets the "ldap_username" field.
func (_c *LdapUserCreate) SetLdapUsername(v string) *LdapUserCreate {
	_c.mutation.SetLdapUsername(v)
	return _c
}

// SetLdapDn sets the "ldap_dn" field.
func (_c *LdapUserCreate) SetLdapDn(v string) *LdapUserCreate {
	_c.mutation.SetLdapDn(v)
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *LdapUserCreate) SetLastSyncAt(v time.Time) *LdapUserCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *LdapUserCreate) SetNillableLastSyncAt(v *time.Time) *LdapUserCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *LdapUserCreate) SetUser(v *User) *LdapUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the LdapUserMutation object of the builder.
func (_c *LdapUserCreate) Mutation() *LdapUserMutation {
	return _c.mutation
}

// Save creates the LdapUser in the database.
func (_c *LdapUserCreate) Save(ctx context.Context) (*LdapUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LdapUserCreate) SaveX(ctx context.Context) *LdapUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LdapUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LdapUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LdapUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ldapuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ldapuser.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.LastSyncAt(); !ok {
		v := ldapuser.DefaultLastSyncAt()
		_c.mutation.SetLastSyncAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LdapUserCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LdapUser.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LdapUser.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "LdapUser.user_id"`)}
	}
	if _, ok := _c.mutation.LdapUsername(); !ok {
		return &ValidationError{Name: "ldap_username", err: errors.New(`ent: missing required field "LdapUser.ldap_username"`)}
	}
	if v, ok := _c.mutation.LdapUsername(); ok {
		if err := ldapuser.LdapUsernameValidator(v); err != nil {
			return &ValidationError{Name: "ldap_username", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LdapDn(); !ok {
		return &ValidationError{Name: "ldap_dn", err: errors.New(`ent: missing required field "LdapUser.ldap_dn"`)}
	}
	if v, ok := _c.mutation.LdapDn(); ok {
		if err := ldapuser.LdapDnValidator(v); err != nil {
			return &ValidationError{Name: "ldap_dn", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_dn": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LastSyncAt(); !ok {
		return &ValidationError{Name: "last_sync_at", err: errors.New(`ent: missing required field "LdapUser.last_sync_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "LdapUser.user"`)}
	}
	return nil
}

func (_c *LdapUserCreate) sqlSave(ctx context.Context) (*LdapUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LdapUserCreate) createSpec() (*LdapUser, *sqlgraph.CreateSpec) {
	var (
		_node = &LdapUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ldapuser.Table, sqlgraph.NewFieldSpec(ldapuser.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ldapuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapuser.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.LdapUsername(); ok {
		_spec.SetField(ldapuser.FieldLdapUsername, field.TypeString, value)
		_node.LdapUsername = value
	}
	if value, ok := _c.mutation.LdapDn(); ok {
		_spec.SetField(ldapuser.FieldLdapDn, field.TypeString, value)
		_node.LdapDn = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(ldapuser.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ldapuser.UserTable,
			Columns: []string{ldapuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LdapUser.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LdapUserUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LdapUserCreate) OnConflict(opts ...sql.ConflictOption) *LdapUserUpsertOne {
	_c.conflict = opts
	return &LdapUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LdapUserCreate) OnConflictColumns(columns ...string) *LdapUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LdapUserUpsertOne{
		create: _c,
	}
}

type (
	// LdapUserUpsertOne is the builder for "upsert"-ing
	//  one LdapUser node.
	LdapUserUpsertOne struct {
		create *LdapUserCreate
	}

	// LdapUserUpsert is the "OnConflict" setter.
	LdapUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapUserUpsert) SetUpdatedAt(v time.Time) *LdapUserUpsert {
	u.Set(ldapuser.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapUserUpsert) UpdateUpdatedAt() *LdapUserUpsert {
	u.SetExcluded(ldapuser.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *LdapUserUpsert) SetUserID(v int64) *LdapUserUpsert {
	u.Set(ldapuser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LdapUserUpsert) UpdateUserID() *LdapUserUpsert {
	u.SetExcluded(ldapuser.FieldUserID)
	return u
}

// SetLdapUsername sets the "ldap_username" field.
func (u *LdapUserUpsert) SetLdapUsername(v string) *LdapUserUpsert {
	u.Set(ldapuser.FieldLdapUsername, v)
	return u
}

// UpdateLdapUsername sets the "ldap_username" field to the value that was provided on create.
func (u *LdapUserUpsert) UpdateLdapUsername() *LdapUserUpsert {
	u.SetExcluded(ldapuser.FieldLdapUsername)
	return u
}

// SetLdapDn sets the "ldap_dn" field.
func (u *LdapUserUpsert) SetLdapDn(v string) *LdapUserUpsert {
	u.Set(ldapuser.FieldLdapDn, v)
	return u
}

// UpdateLdapDn sets the "ldap_dn" field to the value that was provided on create.
func (u *LdapUserUpsert) UpdateLdapDn() *LdapUserUpsert {
	u.SetExcluded(ldapuser.FieldLdapDn)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *LdapUserUpsert) SetLastSyncAt(v time.Time) *LdapUserUpsert {
	u.Set(ldapuser.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *LdapUserUpsert) UpdateLastSyncAt() *LdapUserUpsert {
	u.SetExcluded(ldapuser.FieldLastSyncAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LdapUserUpsertOne) UpdateNewValues() *LdapUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ldapuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LdapUserUpsertOne) Ignore() *LdapUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LdapUserUpsertOne) DoNothing() *LdapUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LdapUserCreate.OnConflict
// documentation for more info.
func (u *LdapUserUpsertOne) Update(set func(*LdapUserUpsert)) *LdapUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LdapUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapUserUpsertOne) SetUpdatedAt(v time.Time) *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapUserUpsertOne) UpdateUpdatedAt() *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LdapUserUpsertOne) SetUserID(v int64) *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LdapUserUpsertOne) UpdateUserID() *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateUserID()
	})
}

// SetLdapUsername sets the "ldap_username" field.
func (u *LdapUserUpsertOne) SetLdapUsername(v string) *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLdapUsername(v)
	})
}

// UpdateLdapUsername sets the "ldap_username" field to the value that was provided on create.
func (u *LdapUserUpsertOne) UpdateLdapUsername() *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLdapUsername()
	})
}

// SetLdapDn sets the "ldap_dn" field.
func (u *LdapUserUpsertOne) SetLdapDn(v string) *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLdapDn(v)
	})
}

// UpdateLdapDn sets the "ldap_dn" field to the value that was provided on create.
func (u *LdapUserUpsertOne) UpdateLdapDn() *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLdapDn()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *LdapUserUpsertOne) SetLastSyncAt(v time.Time) *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *LdapUserUpsertOne) UpdateLastSyncAt() *LdapUserUpsertOne {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLastSyncAt()
	})
}

// Exec executes the query.
func (u *LdapUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LdapUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LdapUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LdapUserUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LdapUserUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LdapUserCreateBulk is the builder for creating many LdapUser entities in bulk.
type LdapUserCreateBulk struct {
	config
	err      error
	builders []*LdapUserCreate
	conflict []sql.ConflictOption
}

// Save creates the LdapUser entities in the database.
func (_c *LdapUserCreateBulk) Save(ctx context.Context) ([]*LdapUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LdapUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LdapUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LdapUserCreateBulk) SaveX(ctx context.Context) []*LdapUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LdapUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LdapUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LdapUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LdapUserUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LdapUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *LdapUserUpsertBulk {
	_c.conflict = opts
	return &LdapUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LdapUserCreateBulk) OnConflictColumns(columns ...string) *LdapUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LdapUserUpsertBulk{
		create: _c,
	}
}

// LdapUserUpsertBulk is the builder for "upsert"-ing
// a bulk of LdapUser nodes.
type LdapUserUpsertBulk struct {
	create *LdapUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LdapUserUpsertBulk) UpdateNewValues() *LdapUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ldapuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LdapUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LdapUserUpsertBulk) Ignore() *LdapUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LdapUserUpsertBulk) DoNothing() *LdapUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LdapUserCreateBulk.OnConflict
// documentation for more info.
func (u *LdapUserUpsertBulk) Update(set func(*LdapUserUpsert)) *LdapUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LdapUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapUserUpsertBulk) SetUpdatedAt(v time.Time) *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapUserUpsertBulk) UpdateUpdatedAt() *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *LdapUserUpsertBulk) SetUserID(v int64) *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *LdapUserUpsertBulk) UpdateUserID() *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateUserID()
	})
}

// SetLdapUsername sets the "ldap_username" field.
func (u *LdapUserUpsertBulk) SetLdapUsername(v string) *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLdapUsername(v)
	})
}

// UpdateLdapUsername sets the "ldap_username" field to the value that was provided on create.
func (u *LdapUserUpsertBulk) UpdateLdapUsername() *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLdapUsername()
	})
}

// SetLdapDn sets the "ldap_dn" field.
func (u *LdapUserUpsertBulk) SetLdapDn(v string) *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLdapDn(v)
	})
}

// UpdateLdapDn sets the "ldap_dn" field to the value that was provided on create.
func (u *LdapUserUpsertBulk) UpdateLdapDn() *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLdapDn()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *LdapUserUpsertBulk) SetLastSyncAt(v time.Time) *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *LdapUserUpsertBulk) UpdateLastSyncAt() *LdapUserUpsertBulk {
	return u.Update(func(s *LdapUserUpsert) {
		s.UpdateLastSyncAt()
	})
}

// Exec executes the query.
func (u *LdapUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LdapUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LdapUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LdapUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
