// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ldapconfig"
)

// LdapConfigCreate is the builder for creating a LdapConfig entity.
type LdapConfigCreate struct {
	config
	mutation *LdapConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *LdapConfigCreate) SetCreatedAt(v time.Time) *LdapConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableCreatedAt(v *time.Time) *LdapConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LdapConfigCreate) SetUpdatedAt(v time.Time) *LdapConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableUpdatedAt(v *time.Time) *LdapConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetServerURL sets the "server_url" field.
func (_c *LdapConfigCreate) SetServerURL(v string) *LdapConfigCreate {
	_c.mutation.SetServerURL(v)
	return _c
}

// SetBindDn sets the "bind_dn" field.
func (_c *LdapConfigCreate) SetBindDn(v string) *LdapConfigCreate {
	_c.mutation.SetBindDn(v)
	return _c
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (_c *LdapConfigCreate) SetBindPasswordEncrypted(v string) *LdapConfigCreate {
	_c.mutation.SetBindPasswordEncrypted(v)
	return _c
}

// SetBaseDn sets the "base_dn" field.
func (_c *LdapConfigCreate) SetBaseDn(v string) *LdapConfigCreate {
	_c.mutation.SetBaseDn(v)
	return _c
}

// SetUserFilter sets the "user_filter" field.
func (_c *LdapConfigCreate) SetUserFilter(v string) *LdapConfigCreate {
	_c.mutation.SetUserFilter(v)
	return _c
}

// SetNillableUserFilter sets the "user_filter" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableUserFilter(v *string) *LdapConfigCreate {
	if v != nil {
		_c.SetUserFilter(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LdapConfigCreate) SetEnabled(v bool) *LdapConfigCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableEnabled(v *bool) *LdapConfigCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetTLSEnabled sets the "tls_enabled" field.
func (_c *LdapConfigCreate) SetTLSEnabled(v bool) *LdapConfigCreate {
	_c.mutation.SetTLSEnabled(v)
	return _c
}

// SetNillableTLSEnabled sets the "tls_enabled" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableTLSEnabled(v *bool) *LdapConfigCreate {
	if v != nil {
		_c.SetTLSEnabled(*v)
	}
	return _c
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (_c *LdapConfigCreate) SetTLSSkipVerify(v bool) *LdapConfigCreate {
	_c.mutation.SetTLSSkipVerify(v)
	return _c
}

// SetNillableTLSSkipVerify sets the "tls_skip_verify" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableTLSSkipVerify(v *bool) *LdapConfigCreate {
	if v != nil {
		_c.SetTLSSkipVerify(*v)
	}
	return _c
}

// SetConfigSource sets the "config_source" field.
func (_c *LdapConfigCreate) SetConfigSource(v string) *LdapConfigCreate {
	_c.mutation.SetConfigSource(v)
	return _c
}

// SetNillableConfigSource sets the "config_source" field if the given value is not nil.
func (_c *LdapConfigCreate) SetNillableConfigSource(v *string) *LdapConfigCreate {
	if v != nil {
		_c.SetConfigSource(*v)
	}
	return _c
}

// Mutation returns the LdapConfigMutation object of the builder.
func (_c *LdapConfigCreate) Mutation() *LdapConfigMutation {
	return _c.mutation
}

// Save creates the LdapConfig in the database.
func (_c *LdapConfigCreate) Save(ctx context.Context) (*LdapConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LdapConfigCreate) SaveX(ctx context.Context) *LdapConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LdapConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LdapConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LdapConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := ldapconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := ldapconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.UserFilter(); !ok {
		v := ldapconfig.DefaultUserFilter
		_c.mutation.SetUserFilter(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := ldapconfig.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.TLSEnabled(); !ok {
		v := ldapconfig.DefaultTLSEnabled
		_c.mutation.SetTLSEnabled(v)
	}
	if _, ok := _c.mutation.TLSSkipVerify(); !ok {
		v := ldapconfig.DefaultTLSSkipVerify
		_c.mutation.SetTLSSkipVerify(v)
	}
	if _, ok := _c.mutation.ConfigSource(); !ok {
		v := ldapconfig.DefaultConfigSource
		_c.mutation.SetConfigSource(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LdapConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LdapConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LdapConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.ServerURL(); !ok {
		return &ValidationError{Name: "server_url", err: errors.New(`ent: missing required field "LdapConfig.server_url"`)}
	}
	if v, ok := _c.mutation.ServerURL(); ok {
		if err := ldapconfig.ServerURLValidator(v); err != nil {
			return &ValidationError{Name: "server_url", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.server_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BindDn(); !ok {
		return &ValidationError{Name: "bind_dn", err: errors.New(`ent: missing required field "LdapConfig.bind_dn"`)}
	}
	if v, ok := _c.mutation.BindDn(); ok {
		if err := ldapconfig.BindDnValidator(v); err != nil {
			return &ValidationError{Name: "bind_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_dn": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BindPasswordEncrypted(); !ok {
		return &ValidationError{Name: "bind_password_encrypted", err: errors.New(`ent: missing required field "LdapConfig.bind_password_encrypted"`)}
	}
	if v, ok := _c.mutation.BindPasswordEncrypted(); ok {
		if err := ldapconfig.BindPasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "bind_password_encrypted", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_password_encrypted": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseDn(); !ok {
		return &ValidationError{Name: "base_dn", err: errors.New(`ent: missing required field "LdapConfig.base_dn"`)}
	}
	if v, ok := _c.mutation.BaseDn(); ok {
		if err := ldapconfig.BaseDnValidator(v); err != nil {
			return &ValidationError{Name: "base_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.base_dn": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserFilter(); !ok {
		return &ValidationError{Name: "user_filter", err: errors.New(`ent: missing required field "LdapConfig.user_filter"`)}
	}
	if v, ok := _c.mutation.UserFilter(); ok {
		if err := ldapconfig.UserFilterValidator(v); err != nil {
			return &ValidationError{Name: "user_filter", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.user_filter": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "LdapConfig.enabled"`)}
	}
	if _, ok := _c.mutation.TLSEnabled(); !ok {
		return &ValidationError{Name: "tls_enabled", err: errors.New(`ent: missing required field "LdapConfig.tls_enabled"`)}
	}
	if _, ok := _c.mutation.TLSSkipVerify(); !ok {
		return &ValidationError{Name: "tls_skip_verify", err: errors.New(`ent: missing required field "LdapConfig.tls_skip_verify"`)}
	}
	if _, ok := _c.mutation.ConfigSource(); !ok {
		return &ValidationError{Name: "config_source", err: errors.New(`ent: missing required field "LdapConfig.config_source"`)}
	}
	if v, ok := _c.mutation.ConfigSource(); ok {
		if err := ldapconfig.ConfigSourceValidator(v); err != nil {
			return &ValidationError{Name: "config_source", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.config_source": %w`, err)}
		}
	}
	return nil
}

func (_c *LdapConfigCreate) sqlSave(ctx context.Context) (*LdapConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LdapConfigCreate) createSpec() (*LdapConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &LdapConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ldapconfig.Table, sqlgraph.NewFieldSpec(ldapconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(ldapconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ServerURL(); ok {
		_spec.SetField(ldapconfig.FieldServerURL, field.TypeString, value)
		_node.ServerURL = value
	}
	if value, ok := _c.mutation.BindDn(); ok {
		_spec.SetField(ldapconfig.FieldBindDn, field.TypeString, value)
		_node.BindDn = value
	}
	if value, ok := _c.mutation.BindPasswordEncrypted(); ok {
		_spec.SetField(ldapconfig.FieldBindPasswordEncrypted, field.TypeString, value)
		_node.BindPasswordEncrypted = value
	}
	if value, ok := _c.mutation.BaseDn(); ok {
		_spec.SetField(ldapconfig.FieldBaseDn, field.TypeString, value)
		_node.BaseDn = value
	}
	if value, ok := _c.mutation.UserFilter(); ok {
		_spec.SetField(ldapconfig.FieldUserFilter, field.TypeString, value)
		_node.UserFilter = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(ldapconfig.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.TLSEnabled(); ok {
		_spec.SetField(ldapconfig.FieldTLSEnabled, field.TypeBool, value)
		_node.TLSEnabled = value
	}
	if value, ok := _c.mutation.TLSSkipVerify(); ok {
		_spec.SetField(ldapconfig.FieldTLSSkipVerify, field.TypeBool, value)
		_node.TLSSkipVerify = value
	}
	if value, ok := _c.mutation.ConfigSource(); ok {
		_spec.SetField(ldapconfig.FieldConfigSource, field.TypeString, value)
		_node.ConfigSource = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LdapConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LdapConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LdapConfigCreate) OnConflict(opts ...sql.ConflictOption) *LdapConfigUpsertOne {
	_c.conflict = opts
	return &LdapConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LdapConfigCreate) OnConflictColumns(columns ...string) *LdapConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LdapConfigUpsertOne{
		create: _c,
	}
}

type (
	// LdapConfigUpsertOne is the builder for "upsert"-ing
	//  one LdapConfig node.
	LdapConfigUpsertOne struct {
		create *LdapConfigCreate
	}

	// LdapConfigUpsert is the "OnConflict" setter.
	LdapConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapConfigUpsert) SetUpdatedAt(v time.Time) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateUpdatedAt() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldUpdatedAt)
	return u
}

// SetServerURL sets the "server_url" field.
func (u *LdapConfigUpsert) SetServerURL(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldServerURL, v)
	return u
}

// UpdateServerURL sets the "server_url" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateServerURL() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldServerURL)
	return u
}

// SetBindDn sets the "bind_dn" field.
func (u *LdapConfigUpsert) SetBindDn(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldBindDn, v)
	return u
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateBindDn() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldBindDn)
	return u
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (u *LdapConfigUpsert) SetBindPasswordEncrypted(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldBindPasswordEncrypted, v)
	return u
}

// UpdateBindPasswordEncrypted sets the "bind_password_encrypted" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateBindPasswordEncrypted() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldBindPasswordEncrypted)
	return u
}

// SetBaseDn sets the "base_dn" field.
func (u *LdapConfigUpsert) SetBaseDn(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldBaseDn, v)
	return u
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateBaseDn() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldBaseDn)
	return u
}

// SetUserFilter sets the "user_filter" field.
func (u *LdapConfigUpsert) SetUserFilter(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldUserFilter, v)
	return u
}

// UpdateUserFilter sets the "user_filter" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateUserFilter() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldUserFilter)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *LdapConfigUpsert) SetEnabled(v bool) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateEnabled() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldEnabled)
	return u
}

// SetTLSEnabled sets the "tls_enabled" field.
func (u *LdapConfigUpsert) SetTLSEnabled(v bool) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldTLSEnabled, v)
	return u
}

// UpdateTLSEnabled sets the "tls_enabled" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateTLSEnabled() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldTLSEnabled)
	return u
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (u *LdapConfigUpsert) SetTLSSkipVerify(v bool) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldTLSSkipVerify, v)
	return u
}

// UpdateTLSSkipVerify sets the "tls_skip_verify" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateTLSSkipVerify() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldTLSSkipVerify)
	return u
}

// SetConfigSource sets the "config_source" field.
func (u *LdapConfigUpsert) SetConfigSource(v string) *LdapConfigUpsert {
	u.Set(ldapconfig.FieldConfigSource, v)
	return u
}

// UpdateConfigSource sets the "config_source" field to the value that was provided on create.
func (u *LdapConfigUpsert) UpdateConfigSource() *LdapConfigUpsert {
	u.SetExcluded(ldapconfig.FieldConfigSource)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LdapConfigUpsertOne) UpdateNewValues() *LdapConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(ldapconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LdapConfigUpsertOne) Ignore() *LdapConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LdapConfigUpsertOne) DoNothing() *LdapConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LdapConfigCreate.OnConflict
// documentation for more info.
func (u *LdapConfigUpsertOne) Update(set func(*LdapConfigUpsert)) *LdapConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LdapConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapConfigUpsertOne) SetUpdatedAt(v time.Time) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateUpdatedAt() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetServerURL sets the "server_url" field.
func (u *LdapConfigUpsertOne) SetServerURL(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetServerURL(v)
	})
}

// UpdateServerURL sets the "server_url" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateServerURL() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateServerURL()
	})
}

// SetBindDn sets the "bind_dn" field.
func (u *LdapConfigUpsertOne) SetBindDn(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBindDn(v)
	})
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateBindDn() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBindDn()
	})
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (u *LdapConfigUpsertOne) SetBindPasswordEncrypted(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBindPasswordEncrypted(v)
	})
}

// UpdateBindPasswordEncrypted sets the "bind_password_encrypted" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateBindPasswordEncrypted() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBindPasswordEncrypted()
	})
}

// SetBaseDn sets the "base_dn" field.
func (u *LdapConfigUpsertOne) SetBaseDn(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBaseDn(v)
	})
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateBaseDn() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBaseDn()
	})
}

// SetUserFilter sets the "user_filter" field.
func (u *LdapConfigUpsertOne) SetUserFilter(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetUserFilter(v)
	})
}

// UpdateUserFilter sets the "user_filter" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateUserFilter() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateUserFilter()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LdapConfigUpsertOne) SetEnabled(v bool) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateEnabled() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetTLSEnabled sets the "tls_enabled" field.
func (u *LdapConfigUpsertOne) SetTLSEnabled(v bool) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetTLSEnabled(v)
	})
}

// UpdateTLSEnabled sets the "tls_enabled" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateTLSEnabled() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateTLSEnabled()
	})
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (u *LdapConfigUpsertOne) SetTLSSkipVerify(v bool) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetTLSSkipVerify(v)
	})
}

// UpdateTLSSkipVerify sets the "tls_skip_verify" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateTLSSkipVerify() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateTLSSkipVerify()
	})
}

// SetConfigSource sets the "config_source" field.
func (u *LdapConfigUpsertOne) SetConfigSource(v string) *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetConfigSource(v)
	})
}

// UpdateConfigSource sets the "config_source" field to the value that was provided on create.
func (u *LdapConfigUpsertOne) UpdateConfigSource() *LdapConfigUpsertOne {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateConfigSource()
	})
}

// Exec executes the query.
func (u *LdapConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LdapConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LdapConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LdapConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LdapConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LdapConfigCreateBulk is the builder for creating many LdapConfig entities in bulk.
type LdapConfigCreateBulk struct {
	config
	err      error
	builders []*LdapConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the LdapConfig entities in the database.
func (_c *LdapConfigCreateBulk) Save(ctx context.Context) ([]*LdapConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LdapConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LdapConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LdapConfigCreateBulk) SaveX(ctx context.Context) []*LdapConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LdapConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LdapConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LdapConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LdapConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *LdapConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *LdapConfigUpsertBulk {
	_c.conflict = opts
	return &LdapConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LdapConfigCreateBulk) OnConflictColumns(columns ...string) *LdapConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LdapConfigUpsertBulk{
		create: _c,
	}
}

// LdapConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of LdapConfig nodes.
type LdapConfigUpsertBulk struct {
	create *LdapConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LdapConfigUpsertBulk) UpdateNewValues() *LdapConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(ldapconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LdapConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LdapConfigUpsertBulk) Ignore() *LdapConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LdapConfigUpsertBulk) DoNothing() *LdapConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LdapConfigCreateBulk.OnConflict
// documentation for more info.
func (u *LdapConfigUpsertBulk) Update(set func(*LdapConfigUpsert)) *LdapConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LdapConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LdapConfigUpsertBulk) SetUpdatedAt(v time.Time) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateUpdatedAt() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetServerURL sets the "server_url" field.
func (u *LdapConfigUpsertBulk) SetServerURL(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetServerURL(v)
	})
}

// UpdateServerURL sets the "server_url" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateServerURL() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateServerURL()
	})
}

// SetBindDn sets the "bind_dn" field.
func (u *LdapConfigUpsertBulk) SetBindDn(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBindDn(v)
	})
}

// UpdateBindDn sets the "bind_dn" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateBindDn() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBindDn()
	})
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (u *LdapConfigUpsertBulk) SetBindPasswordEncrypted(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBindPasswordEncrypted(v)
	})
}

// UpdateBindPasswordEncrypted sets the "bind_password_encrypted" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateBindPasswordEncrypted() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBindPasswordEncrypted()
	})
}

// SetBaseDn sets the "base_dn" field.
func (u *LdapConfigUpsertBulk) SetBaseDn(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetBaseDn(v)
	})
}

// UpdateBaseDn sets the "base_dn" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateBaseDn() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateBaseDn()
	})
}

// SetUserFilter sets the "user_filter" field.
func (u *LdapConfigUpsertBulk) SetUserFilter(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetUserFilter(v)
	})
}

// UpdateUserFilter sets the "user_filter" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateUserFilter() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateUserFilter()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LdapConfigUpsertBulk) SetEnabled(v bool) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateEnabled() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateEnabled()
	})
}

// SetTLSEnabled sets the "tls_enabled" field.
func (u *LdapConfigUpsertBulk) SetTLSEnabled(v bool) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetTLSEnabled(v)
	})
}

// UpdateTLSEnabled sets the "tls_enabled" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateTLSEnabled() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateTLSEnabled()
	})
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (u *LdapConfigUpsertBulk) SetTLSSkipVerify(v bool) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetTLSSkipVerify(v)
	})
}

// UpdateTLSSkipVerify sets the "tls_skip_verify" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateTLSSkipVerify() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateTLSSkipVerify()
	})
}

// SetConfigSource sets the "config_source" field.
func (u *LdapConfigUpsertBulk) SetConfigSource(v string) *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.SetConfigSource(v)
	})
}

// UpdateConfigSource sets the "config_source" field to the value that was provided on create.
func (u *LdapConfigUpsertBulk) UpdateConfigSource() *LdapConfigUpsertBulk {
	return u.Update(func(s *LdapConfigUpsert) {
		s.UpdateConfigSource()
	})
}

// Exec executes the query.
func (u *LdapConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LdapConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LdapConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LdapConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
