// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ldapconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LdapConfigDelete is the builder for deleting a LdapConfig entity.
type LdapConfigDelete struct {
	config
	hooks    []Hook
	mutation *LdapConfigMutation
}

// Where appends a list predicates to the LdapConfigDelete builder.
func (_d *LdapConfigDelete) Where(ps ...predicate.LdapConfig) *LdapConfigDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LdapConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LdapConfigDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LdapConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(ldapconfig.Table, sqlgraph.NewFieldSpec(ldapconfig.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LdapConfigDeleteOne is the builder for deleting a single LdapConfig entity.
type LdapConfigDeleteOne struct {
	_d *LdapConfigDelete
}

// Where appends a list predicates to the LdapConfigDelete builder.
func (_d *LdapConfigDeleteOne) Where(ps ...predicate.LdapConfig) *LdapConfigDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LdapConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{ldapconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LdapConfigDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
