// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ldapuser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LdapUserUpdate is the builder for updating LdapUser entities.
type LdapUserUpdate struct {
	config
	hooks    []Hook
	mutation *LdapUserMutation
}

// Where appends a list predicates to the LdapUserUpdate builder.
func (_u *LdapUserUpdate) Where(ps ...predicate.LdapUser) *LdapUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LdapUserUpdate) SetUpdatedAt(v time.Time) *LdapUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LdapUserUpdate) SetUserID(v int64) *LdapUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LdapUserUpdate) SetNillableUserID(v *int64) *LdapUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLdapUsername sets the "ldap_username" field.
func (_u *LdapUserUpdate) SetLdapUsername(v string) *LdapUserUpdate {
	_u.mutation.SetLdapUsername(v)
	return _u
}

// SetNillableLdapUsername sets the "ldap_username" field if the given value is not nil.
func (_u *LdapUserUpdate) SetNillableLdapUsername(v *string) *LdapUserUpdate {
	if v != nil {
		_u.SetLdapUsername(*v)
	}
	return _u
}

// SetLdapDn sets the "ldap_dn" field.
func (_u *LdapUserUpdate) SetLdapDn(v string) *LdapUserUpdate {
	_u.mutation.SetLdapDn(v)
	return _u
}

// SetNillableLdapDn sets the "ldap_dn" field if the given value is not nil.
func (_u *LdapUserUpdate) SetNillableLdapDn(v *string) *LdapUserUpdate {
	if v != nil {
		_u.SetLdapDn(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *LdapUserUpdate) SetLastSyncAt(v time.Time) *LdapUserUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *LdapUserUpdate) SetNillableLastSyncAt(v *time.Time) *LdapUserUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LdapUserUpdate) SetUser(v *User) *LdapUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the LdapUserMutation object of the builder.
func (_u *LdapUserUpdate) Mutation() *LdapUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LdapUserUpdate) ClearUser() *LdapUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LdapUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LdapUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LdapUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LdapUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LdapUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ldapuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LdapUserUpdate) check() error {
	if v, ok := _u.mutation.LdapUsername(); ok {
		if err := ldapuser.LdapUsernameValidator(v); err != nil {
			return &ValidationError{Name: "ldap_username", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LdapDn(); ok {
		if err := ldapuser.LdapDnValidator(v); err != nil {
			return &ValidationError{Name: "ldap_dn", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_dn": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LdapUser.user"`)
	}
	return nil
}

func (_u *LdapUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ldapuser.Table, ldapuser.Columns, sqlgraph.NewFieldSpec(ldapuser.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LdapUsername(); ok {
		_spec.SetField(ldapuser.FieldLdapUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.LdapDn(); ok {
		_spec.SetField(ldapuser.FieldLdapDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(ldapuser.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ldapuser.UserTable,
			Columns: []string{ldapuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ldapuser.UserTable,
			Columns: []string{ldapuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ldapuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LdapUserUpdateOne is the builder for updating a single LdapUser entity.
type LdapUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LdapUserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LdapUserUpdateOne) SetUpdatedAt(v time.Time) *LdapUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LdapUserUpdateOne) SetUserID(v int64) *LdapUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LdapUserUpdateOne) SetNillableUserID(v *int64) *LdapUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetLdapUsername sets the "ldap_username" field.
func (_u *LdapUserUpdateOne) SetLdapUsername(v string) *LdapUserUpdateOne {
	_u.mutation.SetLdapUsername(v)
	return _u
}

// SetNillableLdapUsername sets the "ldap_username" field if the given value is not nil.
func (_u *LdapUserUpdateOne) SetNillableLdapUsername(v *string) *LdapUserUpdateOne {
	if v != nil {
		_u.SetLdapUsername(*v)
	}
	return _u
}

// SetLdapDn sets the "ldap_dn" field.
func (_u *LdapUserUpdateOne) SetLdapDn(v string) *LdapUserUpdateOne {
	_u.mutation.SetLdapDn(v)
	return _u
}

// SetNillableLdapDn sets the "ldap_dn" field if the given value is not nil.
func (_u *LdapUserUpdateOne) SetNillableLdapDn(v *string) *LdapUserUpdateOne {
	if v != nil {
		_u.SetLdapDn(*v)
	}
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *LdapUserUpdateOne) SetLastSyncAt(v time.Time) *LdapUserUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *LdapUserUpdateOne) SetNillableLastSyncAt(v *time.Time) *LdapUserUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *LdapUserUpdateOne) SetUser(v *User) *LdapUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the LdapUserMutation object of the builder.
func (_u *LdapUserUpdateOne) Mutation() *LdapUserMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *LdapUserUpdateOne) ClearUser() *LdapUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the LdapUserUpdate builder.
func (_u *LdapUserUpdateOne) Where(ps ...predicate.LdapUser) *LdapUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LdapUserUpdateOne) Select(field string, fields ...string) *LdapUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LdapUser entity.
func (_u *LdapUserUpdateOne) Save(ctx context.Context) (*LdapUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LdapUserUpdateOne) SaveX(ctx context.Context) *LdapUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LdapUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LdapUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LdapUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ldapuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LdapUserUpdateOne) check() error {
	if v, ok := _u.mutation.LdapUsername(); ok {
		if err := ldapuser.LdapUsernameValidator(v); err != nil {
			return &ValidationError{Name: "ldap_username", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LdapDn(); ok {
		if err := ldapuser.LdapDnValidator(v); err != nil {
			return &ValidationError{Name: "ldap_dn", err: fmt.Errorf(`ent: validator failed for field "LdapUser.ldap_dn": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "LdapUser.user"`)
	}
	return nil
}

func (_u *LdapUserUpdateOne) sqlSave(ctx context.Context) (_node *LdapUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ldapuser.Table, ldapuser.Columns, sqlgraph.NewFieldSpec(ldapuser.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LdapUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ldapuser.FieldID)
		for _, f := range fields {
			if !ldapuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ldapuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LdapUsername(); ok {
		_spec.SetField(ldapuser.FieldLdapUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.LdapDn(); ok {
		_spec.SetField(ldapuser.FieldLdapDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(ldapuser.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ldapuser.UserTable,
			Columns: []string{ldapuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ldapuser.UserTable,
			Columns: []string{ldapuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &LdapUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ldapuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
