// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ldapuser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// LdapUser is the model entity for the LdapUser schema.
type LdapUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Foreign key to users table
	UserID int64 `json:"user_id,omitempty"`
	// LDAP username (uid)
	LdapUsername string `json:"ldap_username,omitempty"`
	// LDAP Distinguished Name
	LdapDn string `json:"ldap_dn,omitempty"`
	// Last synchronization time
	LastSyncAt time.Time `json:"last_sync_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LdapUserQuery when eager-loading is set.
	Edges        LdapUserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// LdapUserEdges holds the relations/edges for other nodes in the graph.
type LdapUserEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LdapUserEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LdapUser) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ldapuser.FieldID, ldapuser.FieldUserID:
			values[i] = new(sql.NullInt64)
		case ldapuser.FieldLdapUsername, ldapuser.FieldLdapDn:
			values[i] = new(sql.NullString)
		case ldapuser.FieldCreatedAt, ldapuser.FieldUpdatedAt, ldapuser.FieldLastSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LdapUser fields.
func (_m *LdapUser) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ldapuser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ldapuser.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ldapuser.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ldapuser.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case ldapuser.FieldLdapUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ldap_username", values[i])
			} else if value.Valid {
				_m.LdapUsername = value.String
			}
		case ldapuser.FieldLdapDn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ldap_dn", values[i])
			} else if value.Valid {
				_m.LdapDn = value.String
			}
		case ldapuser.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LdapUser.
// This includes values selected through modifiers, order, etc.
func (_m *LdapUser) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the LdapUser entity.
func (_m *LdapUser) QueryUser() *UserQuery {
	return NewLdapUserClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this LdapUser.
// Note that you need to call LdapUser.Unwrap() before calling this method if this LdapUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LdapUser) Update() *LdapUserUpdateOne {
	return NewLdapUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LdapUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LdapUser) Unwrap() *LdapUser {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LdapUser is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LdapUser) String() string {
	var builder strings.Builder
	builder.WriteString("LdapUser(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("ldap_username=")
	builder.WriteString(_m.LdapUsername)
	builder.WriteString(", ")
	builder.WriteString("ldap_dn=")
	builder.WriteString(_m.LdapDn)
	builder.WriteString(", ")
	builder.WriteString("last_sync_at=")
	builder.WriteString(_m.LastSyncAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LdapUsers is a parsable slice of LdapUser.
type LdapUsers []*LdapUser
