// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/ldapconfig"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LdapConfigUpdate is the builder for updating LdapConfig entities.
type LdapConfigUpdate struct {
	config
	hooks    []Hook
	mutation *LdapConfigMutation
}

// Where appends a list predicates to the LdapConfigUpdate builder.
func (_u *LdapConfigUpdate) Where(ps ...predicate.LdapConfig) *LdapConfigUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LdapConfigUpdate) SetUpdatedAt(v time.Time) *LdapConfigUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerURL sets the "server_url" field.
func (_u *LdapConfigUpdate) SetServerURL(v string) *LdapConfigUpdate {
	_u.mutation.SetServerURL(v)
	return _u
}

// SetNillableServerURL sets the "server_url" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableServerURL(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetServerURL(*v)
	}
	return _u
}

// SetBindDn sets the "bind_dn" field.
func (_u *LdapConfigUpdate) SetBindDn(v string) *LdapConfigUpdate {
	_u.mutation.SetBindDn(v)
	return _u
}

// SetNillableBindDn sets the "bind_dn" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableBindDn(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetBindDn(*v)
	}
	return _u
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (_u *LdapConfigUpdate) SetBindPasswordEncrypted(v string) *LdapConfigUpdate {
	_u.mutation.SetBindPasswordEncrypted(v)
	return _u
}

// SetNillableBindPasswordEncrypted sets the "bind_password_encrypted" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableBindPasswordEncrypted(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetBindPasswordEncrypted(*v)
	}
	return _u
}

// SetBaseDn sets the "base_dn" field.
func (_u *LdapConfigUpdate) SetBaseDn(v string) *LdapConfigUpdate {
	_u.mutation.SetBaseDn(v)
	return _u
}

// SetNillableBaseDn sets the "base_dn" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableBaseDn(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetBaseDn(*v)
	}
	return _u
}

// SetUserFilter sets the "user_filter" field.
func (_u *LdapConfigUpdate) SetUserFilter(v string) *LdapConfigUpdate {
	_u.mutation.SetUserFilter(v)
	return _u
}

// SetNillableUserFilter sets the "user_filter" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableUserFilter(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetUserFilter(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LdapConfigUpdate) SetEnabled(v bool) *LdapConfigUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableEnabled(v *bool) *LdapConfigUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTLSEnabled sets the "tls_enabled" field.
func (_u *LdapConfigUpdate) SetTLSEnabled(v bool) *LdapConfigUpdate {
	_u.mutation.SetTLSEnabled(v)
	return _u
}

// SetNillableTLSEnabled sets the "tls_enabled" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableTLSEnabled(v *bool) *LdapConfigUpdate {
	if v != nil {
		_u.SetTLSEnabled(*v)
	}
	return _u
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (_u *LdapConfigUpdate) SetTLSSkipVerify(v bool) *LdapConfigUpdate {
	_u.mutation.SetTLSSkipVerify(v)
	return _u
}

// SetNillableTLSSkipVerify sets the "tls_skip_verify" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableTLSSkipVerify(v *bool) *LdapConfigUpdate {
	if v != nil {
		_u.SetTLSSkipVerify(*v)
	}
	return _u
}

// SetConfigSource sets the "config_source" field.
func (_u *LdapConfigUpdate) SetConfigSource(v string) *LdapConfigUpdate {
	_u.mutation.SetConfigSource(v)
	return _u
}

// SetNillableConfigSource sets the "config_source" field if the given value is not nil.
func (_u *LdapConfigUpdate) SetNillableConfigSource(v *string) *LdapConfigUpdate {
	if v != nil {
		_u.SetConfigSource(*v)
	}
	return _u
}

// Mutation returns the LdapConfigMutation object of the builder.
func (_u *LdapConfigUpdate) Mutation() *LdapConfigMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LdapConfigUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LdapConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LdapConfigUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LdapConfigUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LdapConfigUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ldapconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LdapConfigUpdate) check() error {
	if v, ok := _u.mutation.ServerURL(); ok {
		if err := ldapconfig.ServerURLValidator(v); err != nil {
			return &ValidationError{Name: "server_url", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.server_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindDn(); ok {
		if err := ldapconfig.BindDnValidator(v); err != nil {
			return &ValidationError{Name: "bind_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_dn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindPasswordEncrypted(); ok {
		if err := ldapconfig.BindPasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "bind_password_encrypted", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_password_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseDn(); ok {
		if err := ldapconfig.BaseDnValidator(v); err != nil {
			return &ValidationError{Name: "base_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.base_dn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserFilter(); ok {
		if err := ldapconfig.UserFilterValidator(v); err != nil {
			return &ValidationError{Name: "user_filter", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.user_filter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigSource(); ok {
		if err := ldapconfig.ConfigSourceValidator(v); err != nil {
			return &ValidationError{Name: "config_source", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.config_source": %w`, err)}
		}
	}
	return nil
}

func (_u *LdapConfigUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ldapconfig.Table, ldapconfig.Columns, sqlgraph.NewFieldSpec(ldapconfig.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServerURL(); ok {
		_spec.SetField(ldapconfig.FieldServerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindDn(); ok {
		_spec.SetField(ldapconfig.FieldBindDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindPasswordEncrypted(); ok {
		_spec.SetField(ldapconfig.FieldBindPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseDn(); ok {
		_spec.SetField(ldapconfig.FieldBaseDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserFilter(); ok {
		_spec.SetField(ldapconfig.FieldUserFilter, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ldapconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSEnabled(); ok {
		_spec.SetField(ldapconfig.FieldTLSEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSSkipVerify(); ok {
		_spec.SetField(ldapconfig.FieldTLSSkipVerify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigSource(); ok {
		_spec.SetField(ldapconfig.FieldConfigSource, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ldapconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LdapConfigUpdateOne is the builder for updating a single LdapConfig entity.
type LdapConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LdapConfigMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LdapConfigUpdateOne) SetUpdatedAt(v time.Time) *LdapConfigUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetServerURL sets the "server_url" field.
func (_u *LdapConfigUpdateOne) SetServerURL(v string) *LdapConfigUpdateOne {
	_u.mutation.SetServerURL(v)
	return _u
}

// SetNillableServerURL sets the "server_url" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableServerURL(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetServerURL(*v)
	}
	return _u
}

// SetBindDn sets the "bind_dn" field.
func (_u *LdapConfigUpdateOne) SetBindDn(v string) *LdapConfigUpdateOne {
	_u.mutation.SetBindDn(v)
	return _u
}

// SetNillableBindDn sets the "bind_dn" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableBindDn(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetBindDn(*v)
	}
	return _u
}

// SetBindPasswordEncrypted sets the "bind_password_encrypted" field.
func (_u *LdapConfigUpdateOne) SetBindPasswordEncrypted(v string) *LdapConfigUpdateOne {
	_u.mutation.SetBindPasswordEncrypted(v)
	return _u
}

// SetNillableBindPasswordEncrypted sets the "bind_password_encrypted" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableBindPasswordEncrypted(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetBindPasswordEncrypted(*v)
	}
	return _u
}

// SetBaseDn sets the "base_dn" field.
func (_u *LdapConfigUpdateOne) SetBaseDn(v string) *LdapConfigUpdateOne {
	_u.mutation.SetBaseDn(v)
	return _u
}

// SetNillableBaseDn sets the "base_dn" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableBaseDn(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetBaseDn(*v)
	}
	return _u
}

// SetUserFilter sets the "user_filter" field.
func (_u *LdapConfigUpdateOne) SetUserFilter(v string) *LdapConfigUpdateOne {
	_u.mutation.SetUserFilter(v)
	return _u
}

// SetNillableUserFilter sets the "user_filter" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableUserFilter(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetUserFilter(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LdapConfigUpdateOne) SetEnabled(v bool) *LdapConfigUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableEnabled(v *bool) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetTLSEnabled sets the "tls_enabled" field.
func (_u *LdapConfigUpdateOne) SetTLSEnabled(v bool) *LdapConfigUpdateOne {
	_u.mutation.SetTLSEnabled(v)
	return _u
}

// SetNillableTLSEnabled sets the "tls_enabled" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableTLSEnabled(v *bool) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetTLSEnabled(*v)
	}
	return _u
}

// SetTLSSkipVerify sets the "tls_skip_verify" field.
func (_u *LdapConfigUpdateOne) SetTLSSkipVerify(v bool) *LdapConfigUpdateOne {
	_u.mutation.SetTLSSkipVerify(v)
	return _u
}

// SetNillableTLSSkipVerify sets the "tls_skip_verify" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableTLSSkipVerify(v *bool) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetTLSSkipVerify(*v)
	}
	return _u
}

// SetConfigSource sets the "config_source" field.
func (_u *LdapConfigUpdateOne) SetConfigSource(v string) *LdapConfigUpdateOne {
	_u.mutation.SetConfigSource(v)
	return _u
}

// SetNillableConfigSource sets the "config_source" field if the given value is not nil.
func (_u *LdapConfigUpdateOne) SetNillableConfigSource(v *string) *LdapConfigUpdateOne {
	if v != nil {
		_u.SetConfigSource(*v)
	}
	return _u
}

// Mutation returns the LdapConfigMutation object of the builder.
func (_u *LdapConfigUpdateOne) Mutation() *LdapConfigMutation {
	return _u.mutation
}

// Where appends a list predicates to the LdapConfigUpdate builder.
func (_u *LdapConfigUpdateOne) Where(ps ...predicate.LdapConfig) *LdapConfigUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LdapConfigUpdateOne) Select(field string, fields ...string) *LdapConfigUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LdapConfig entity.
func (_u *LdapConfigUpdateOne) Save(ctx context.Context) (*LdapConfig, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LdapConfigUpdateOne) SaveX(ctx context.Context) *LdapConfig {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LdapConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LdapConfigUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LdapConfigUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ldapconfig.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LdapConfigUpdateOne) check() error {
	if v, ok := _u.mutation.ServerURL(); ok {
		if err := ldapconfig.ServerURLValidator(v); err != nil {
			return &ValidationError{Name: "server_url", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.server_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindDn(); ok {
		if err := ldapconfig.BindDnValidator(v); err != nil {
			return &ValidationError{Name: "bind_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_dn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindPasswordEncrypted(); ok {
		if err := ldapconfig.BindPasswordEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "bind_password_encrypted", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.bind_password_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseDn(); ok {
		if err := ldapconfig.BaseDnValidator(v); err != nil {
			return &ValidationError{Name: "base_dn", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.base_dn": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserFilter(); ok {
		if err := ldapconfig.UserFilterValidator(v); err != nil {
			return &ValidationError{Name: "user_filter", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.user_filter": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ConfigSource(); ok {
		if err := ldapconfig.ConfigSourceValidator(v); err != nil {
			return &ValidationError{Name: "config_source", err: fmt.Errorf(`ent: validator failed for field "LdapConfig.config_source": %w`, err)}
		}
	}
	return nil
}

func (_u *LdapConfigUpdateOne) sqlSave(ctx context.Context) (_node *LdapConfig, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ldapconfig.Table, ldapconfig.Columns, sqlgraph.NewFieldSpec(ldapconfig.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LdapConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ldapconfig.FieldID)
		for _, f := range fields {
			if !ldapconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ldapconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ldapconfig.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ServerURL(); ok {
		_spec.SetField(ldapconfig.FieldServerURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindDn(); ok {
		_spec.SetField(ldapconfig.FieldBindDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindPasswordEncrypted(); ok {
		_spec.SetField(ldapconfig.FieldBindPasswordEncrypted, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseDn(); ok {
		_spec.SetField(ldapconfig.FieldBaseDn, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserFilter(); ok {
		_spec.SetField(ldapconfig.FieldUserFilter, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(ldapconfig.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSEnabled(); ok {
		_spec.SetField(ldapconfig.FieldTLSEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TLSSkipVerify(); ok {
		_spec.SetField(ldapconfig.FieldTLSSkipVerify, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ConfigSource(); ok {
		_spec.SetField(ldapconfig.FieldConfigSource, field.TypeString, value)
	}
	_node = &LdapConfig{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ldapconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
