// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/ldapconfig"
)

// LdapConfig is the model entity for the LdapConfig schema.
type LdapConfig struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LDAP server URL (e.g., ldap://ldap.example.com:389)
	ServerURL string `json:"server_url,omitempty"`
	// Bind DN for LDAP authentication
	BindDn string `json:"bind_dn,omitempty"`
	// Encrypted bind password (AES-256-GCM)
	BindPasswordEncrypted string `json:"-"`
	// Base DN for user search
	BaseDn string `json:"base_dn,omitempty"`
	// LDAP user filter template
	UserFilter string `json:"user_filter,omitempty"`
	// Whether this LDAP config is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Whether to use LDAP over TLS (ldaps://)
	TLSEnabled bool `json:"tls_enabled,omitempty"`
	// Whether to skip TLS certificate verification
	TLSSkipVerify bool `json:"tls_skip_verify,omitempty"`
	// Configuration source: 'env' or 'database'
	ConfigSource string `json:"config_source,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LdapConfig) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ldapconfig.FieldEnabled, ldapconfig.FieldTLSEnabled, ldapconfig.FieldTLSSkipVerify:
			values[i] = new(sql.NullBool)
		case ldapconfig.FieldID:
			values[i] = new(sql.NullInt64)
		case ldapconfig.FieldServerURL, ldapconfig.FieldBindDn, ldapconfig.FieldBindPasswordEncrypted, ldapconfig.FieldBaseDn, ldapconfig.FieldUserFilter, ldapconfig.FieldConfigSource:
			values[i] = new(sql.NullString)
		case ldapconfig.FieldCreatedAt, ldapconfig.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LdapConfig fields.
func (_m *LdapConfig) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ldapconfig.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case ldapconfig.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case ldapconfig.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case ldapconfig.FieldServerURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server_url", values[i])
			} else if value.Valid {
				_m.ServerURL = value.String
			}
		case ldapconfig.FieldBindDn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_dn", values[i])
			} else if value.Valid {
				_m.BindDn = value.String
			}
		case ldapconfig.FieldBindPasswordEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bind_password_encrypted", values[i])
			} else if value.Valid {
				_m.BindPasswordEncrypted = value.String
			}
		case ldapconfig.FieldBaseDn:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_dn", values[i])
			} else if value.Valid {
				_m.BaseDn = value.String
			}
		case ldapconfig.FieldUserFilter:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_filter", values[i])
			} else if value.Valid {
				_m.UserFilter = value.String
			}
		case ldapconfig.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case ldapconfig.FieldTLSEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tls_enabled", values[i])
			} else if value.Valid {
				_m.TLSEnabled = value.Bool
			}
		case ldapconfig.FieldTLSSkipVerify:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field tls_skip_verify", values[i])
			} else if value.Valid {
				_m.TLSSkipVerify = value.Bool
			}
		case ldapconfig.FieldConfigSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field config_source", values[i])
			} else if value.Valid {
				_m.ConfigSource = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LdapConfig.
// This includes values selected through modifiers, order, etc.
func (_m *LdapConfig) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LdapConfig.
// Note that you need to call LdapConfig.Unwrap() before calling this method if this LdapConfig
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LdapConfig) Update() *LdapConfigUpdateOne {
	return NewLdapConfigClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LdapConfig entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LdapConfig) Unwrap() *LdapConfig {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LdapConfig is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LdapConfig) String() string {
	var builder strings.Builder
	builder.WriteString("LdapConfig(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("server_url=")
	builder.WriteString(_m.ServerURL)
	builder.WriteString(", ")
	builder.WriteString("bind_dn=")
	builder.WriteString(_m.BindDn)
	builder.WriteString(", ")
	builder.WriteString("bind_password_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("base_dn=")
	builder.WriteString(_m.BaseDn)
	builder.WriteString(", ")
	builder.WriteString("user_filter=")
	builder.WriteString(_m.UserFilter)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("tls_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.TLSEnabled))
	builder.WriteString(", ")
	builder.WriteString("tls_skip_verify=")
	builder.WriteString(fmt.Sprintf("%v", _m.TLSSkipVerify))
	builder.WriteString(", ")
	builder.WriteString("config_source=")
	builder.WriteString(_m.ConfigSource)
	builder.WriteByte(')')
	return builder.String()
}

// LdapConfigs is a parsable slice of LdapConfig.
type LdapConfigs []*LdapConfig
